export const style = theme => ({
  avatar:{
    backgroundColor:theme.palette.primary.main
  },
  dialogTitle:{
    textTransform:'capitalize'
  },
  card:{
    marginBottom:5,
    padding:10
  },
  row:{
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
  },
  name:{
    marginLeft:10
  }
})
